// +build !ignore_autogenerated

// Code generated by mga tool. DO NOT EDIT.

package pkeservice

import (
	"context"
	"github.com/banzaicloud/pipeline/internal/cluster"
	"github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock for the Service type.
type MockService struct {
	mock.Mock
}

// RegisterNodeStatus provides a mock function.
func (_m *MockService) RegisterNodeStatus(ctx context.Context, clusterIdentifier cluster.Identifier, nodeStatus NodeStatus) (err error) {
	ret := _m.Called(ctx, clusterIdentifier, nodeStatus)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, cluster.Identifier, NodeStatus) error); ok {
		r0 = rf(ctx, clusterIdentifier, nodeStatus)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
